crrr/root/models/application.py
from crrr import db
from datetime import datetime


class Status(object):
    NEW = 'new'
    INIT = 'initial contact made'
    ARRANGE_HC = 'arranging hc'
    HC_COMPLETED = 'hc completed'
    APPROVED = 'approved'
    UNAPPROVED = 'unapproved'


class App(db.Model):
    __tablename__ = 'app'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    dog_id = db.Column(db.Integer, db.ForeignKey('dog.id'))
    assignee_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    submittal_date = db.Column(db.DateTime, default=datetime.now)
    status = db.Column(db.Enum(Status.NEW,
                               Status.INIT,
                               Status.ARRANGE_HC,
                               Status.HC_COMPLETED,
                               Status.APPROVED,
                               Status.UNAPPROVED,
                               name='app_status'),
                       default=Status.NEW)
    archive = db.Column(db.Boolean, default=False)

    # relationships
    applicant = db.relationship('User', foreign_keys=[user_id], backref='apps',
                                uselist=False)
    assignee = db.relationship('User', foreign_keys=[assignee_id],
                               uselist=False)
    dog = db.relationship('Dog', backref='apps', uselist=False)

    def __repr__(self):
        return "<App for %s is %s>" % (self.dog, self.status)

crrr/application/views.py
from datetime import datetime
from sqlalchemy.sql.expression import asc, desc
from flask import request, render_template, g, Blueprint
from flask.ext.mail import Message
from flask.ext.login import login_required
from crrr import app, mail, db
from crrr.root.forms import Application
from crrr.root.models import App
from crrr.dogs.models import Dog
from crrr.admin.models import (
    User,
    Address,
    Profile,
    Pet,
    Employment,
    Family,
    Phone,
)

mod = Blueprint('application', __name__, url_prefix='/application')


def str_to_bool(foo):
    return True if foo.lower() in ['y', 'yes', 'true', '1'] else False


def _store_application(form):
    """Stores the POSTed form in the database."""
    app = App()

    # Look to see if this user has already submitted previous applications
    user = User.query.filter_by(email=form.email.data).first()
    if user is None:
        user = User(username=form.email.data,
                    email=form.email.data,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    password='changeme',
                    active=False)

    home = Address(location='home',
                   line_1=form.addr_1.data,
                   line_2=form.addr_2.data,
                   city=form.city.data,
                   state=form.state.data,
                   zip=form.zip_code.data,
                   duration=form.address_length.data)

    vet = Address(location='vet',
                  clinic=form.ref1_firstname.data,
                  vet_name=form.ref1_lastname.data,
                  line_1=form.ref1_address1.data,
                  line_2=form.ref1_address2.data,
                  city=form.ref1_city.data,
                  state=form.ref1_state.data,
                  zip=form.ref1_zip.data)

    phone = Phone(number=form.ref1_phone.data, location='work')
    vet.phones.append(phone)
    user.addresses.extend([home, vet])

    # Get the user's phone numbers
    home = Phone(number=form.phone_h.data, location='home')
    cell = Phone(number=form.phone_c.data, location='cell')
    work = Phone(number=form.phone_w.data, location='work')
    phones = [p for p in [home, cell, work] if p]
    user.phones.extend(phones)

    # Get their employment information
    work = Employment(name=form.employer.data,
                      occupation=form.occupation.data,
                      status=form.employment_type.data)
    user.employment.append(work)

    # Do they have any family?  Record all of their relationships.
    fam1 = Family(relation=form.relation1.data, name=form.name1.data)
    fam2 = Family(relation=form.relation2.data, name=form.name2.data)
    fam3 = Family(relation=form.relation3.data, name=form.name3.data)
    fam4 = Family(relation=form.relation4.data, name=form.name4.data)
    fam5 = Family(relation=form.relation5.data, name=form.name5.data)
    family = [f for f in [fam1, fam2, fam3, fam4, fam5] if f]
    user.relations.extend(family)

    # Did they have any pets?
    def _create_pet(form, pet_num):
        species = getattr(form, 'pet_{num}_species'.format(num=pet_num))
        name = getattr(form, 'pet_{num}_name'.format(num=pet_num))
        gender = getattr(form, 'pet_{num}_sex'.format(num=pet_num))
        age = getattr(form, 'pet_{num}_age'.format(num=pet_num))
        altered = getattr(form, 'pet_{num}_altered'.format(num=pet_num))
        whathappened = getattr(form, 'pet_{num}_whathappened'.format(num=pet_num))
        p = Pet(type=species.data,
                name=name.data,
                gender=gender.data,
                age=age.data,
                altered=str_to_bool(altered.data),
                whathappened=whathappened.data)
        return p
    pets = [_create_pet(form, i) for i in range(1, 6)]
    pets = [p for p in pets if p]
    if pets:
        user.pets.extend(pets)

    # Now for their profile, aka the guts of the application
    p = Profile(free_feed=str_to_bool(form.freefeed.data),
                who_cares=form.whocares.data,
                home=form.home.data,
                needs=form.needs.data,
                alone_time=form.alonetime.data,
                dog_kept_home=str(form.dogkepthome.data),
                dog_kept_away=str(form.dogkeptaway.data),
                dog_door=form.dogdoor.data,
                transport=form.transport.data,
                crate=form.crate.data,
                sleep=form.sleep.data,
                why_ridgebacks=str(form.whyridgebacks.data),
                before_pets=form.before.data,
                expenses=form.expenses.data,
                day_in_the_life=form.dayinthelife.data,
                dog_as_family=form.dogasfamily.data,
                activity_level=form.activitylevel.data,
                away_care=form.awaycare.data,
                give_up=form.giveup.data,
                housing=form.housing.data,
                own_rent=form.ownrent.data,
                landlord_proof=form.landlordproof.data,
                yard=form.yard.data,
                fence=form.fence.data,
                fence_details=form.fencedetails.data,
                ridgeback_gender=form.ridgebackgender.data,
                ridgeback_age=form.ridgebackage.data,
                ridgeback_ridges=form.ridgebackridges.data,
                ridgeback_purebred=form.ridgebackpurebred.data,
                ridgeback_health_problems=form.ridgebackhealthproblems.data,
                ridgeback_social_problems=form.ridgebacksocialproblems.data)
    user.profile = p

    # Assign this application to an admin
    app.assignee = User.query.filter_by(role=1).first()

    # If they specified a particular dog, associate it.
    app.dog = Dog.query.filter_by(name=form.ridgebackname.data).first()

    # Now tie up the associations and store in the db
    app.applicant = user
    db.session.add(user)
    db.session.add(app)
    db.session.commit()


@mod.route('/all/')
@login_required
def all():
    q = App.query
    if not request.args.get('showarchivedapps'):
        q = q.filter(App.archive == False)  # noqa
    if request.args.get('dateasc'):
        q = q.order_by(asc(App.submittal_date))
    else:
        q = q.order_by(desc(App.submittal_date))
    apps = q.all()
    return render_template('application/all.html', apps=apps)


@mod.route('/<int:id>/')
@login_required
def view(id):
    app = App.query.get_or_404(id)
    user = app.applicant
    home_addr = [addr for addr in user.addresses if addr.location == 'home'][0]
    vet_addr = [addr for addr in user.addresses if addr.location == 'vet'][0]
    home_phone = [p for p in user.phones if p.location == 'home'][0]
    cell_phone = [p for p in user.phones if p.location == 'cell'][0]
    work_phone = [p for p in user.phones if p.location == 'work'][0]
    work = user.employment[0]

    kwargs = dict(
        first_name=user.first_name,
        last_name=user.last_name,
        addr_1=home_addr.line_1,
        addr_2=home_addr.line_2,
        city=home_addr.city,
        state=home_addr.state,
        zip_code=home_addr.zip,
        address_length=home_addr.duration,
        email=user.email,
        phone_h=home_phone.number,
        phone_c=cell_phone.number,
        phone_w=work_phone.number,
        employer=work.name,
        occupation=work.occupation,
        employment_type=work.status,
        kids=user.profile.kid_info,
        ref1_firstname=vet_addr.clinic,
        ref1_lastname=vet_addr.vet_name,
        ref1_address1=vet_addr.line_1,
        ref1_address2=vet_addr.line_2,
        ref1_city=vet_addr.city,
        ref1_state=vet_addr.state,
        ref1_zip=vet_addr.zip,
        ref1_phone=vet_addr.phones[0].number,
        # Profile information..
        freefeed=user.profile.free_feed,
        whocares=user.profile.who_cares,
        home=user.profile.home,
        needs=user.profile.needs,
        alonetime=user.profile.alone_time,
        dogkepthome=user.profile.dog_kept_home.split(','),
        dogkeptaway=user.profile.dog_kept_away.split(','),
        dogdoor=user.profile.dog_door,
        transport=user.profile.transport,
        crate=user.profile.crate,
        sleep=user.profile.sleep,
        whyridgebacks=user.profile.why_ridgebacks.split(','),
        before=user.profile.before_pets,
        expenses=user.profile.expenses,
        dayinthelife=user.profile.day_in_the_life,
        dogasfamily=user.profile.dog_as_family,
        activitylevel=user.profile.activity_level,
        awaycare=user.profile.away_care,
        giveup=user.profile.give_up,
        housing=user.profile.housing,
        ownrent=user.profile.own_rent,
        landlordproof=user.profile.landlord_proof,
        yard=user.profile.yard,
        fence=user.profile.fence,
        fencedetails=user.profile.fence_details,
        ridgebackname=app.dog.name if app.dog else None,
        ridgebackgender=user.profile.ridgeback_gender,
        ridgebackage=user.profile.ridgeback_age,
        ridgebackridges=user.profile.ridgeback_ridges,
        ridgebackpurebred=user.profile.ridgeback_purebred,
        ridgebackhealthproblems=user.profile.ridgeback_health_problems,
        ridgebacksocialproblems=user.profile.ridgeback_social_problems,
    )
    # Set the relationships
    for i, r in enumerate(user.relations):
        kwargs.update({
            'relation{}'.format(i + 1): r.relation,
            'name{}'.format(i + 1): r.name
        })

    # Set the pet information
    for i, pet in enumerate(user.pets):
        kwargs.update({
            'pet_{}_species'.format(i + 1): pet.type,
            'pet_{}_name'.format(i + 1): pet.name,
            'pet_{}_sex'.format(i + 1): pet.gender,
            'pet_{}_age'.format(i + 1): pet.age,
            'pet_{}_altered'.format(i + 1): pet.altered,
            'pet_{}_whathappened'.format(i + 1): pet.whathappened,
        })
    form = Application(**kwargs)
    return render_template('application/view.html', form=form)

crrr/templates/application/all.html
{% extends "layout.html" %}
{% block content %}
{% if apps %}
<div class="header">
    <h1 class="content-subhead">Current Applications</h1>
</div>
<table class="pure-table pure-table-striped center">
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Status</th>
      <th>
        {% if request.args.get("dateasc") %}
        <a href={{ url_for('application.all') }}>Date</a>
        {% else %}
        <a href={{ url_for('application.all', dateasc=True) }}>Date</a>
        {% endif %}
      </th>
      <th>
        {% if request.args.get("showarchivedapps") %}
        <a href="{{ url_for('application.all') }}">Archived</a></th>
        {% else %}
        <a href="{{ url_for('application.all', showarchivedapps=True) }}">Archived</a>
        {% endif %}
      </th>
    </tr>
  </thead>
  <tbody>
  {% for app in apps %}
  <tr>
      <td><a href={{ url_for('application.view', id=app.id) }}>{{ app.applicant.last_name|capitalize }}, {{ app.applicant.first_name|capitalize }}</a></td>
      <td>{{ app.status|capitalize }}</td>
      <td>{{ app.submittal_date.strftime("%Y-%m-%d") }}</td>
      <td>{{ app.archived }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No applications are currently in the system.</p>
{% endif %}
{% endblock %}

crrr/templates/application/view.html
{% extends "layout.html" %}
{% block content %}
{% from "_helpers.html" import render %}
{% if form %}
  <form method="POST" action={{ url_for('application.apply') }} class="pure-form pure-form-aligned" id="application">
    {{ form.hidden_tag() }}
    {% if form.errors %}
    <p class="missing">Oh no!  Your application hasn't passed our validation!  Please ensure the following required fields are filled
in properly:</p>
    <ul class="missing">
      {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
          <li>{{ form[field_name].label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
      <legend>Personal Information</legend>
      {{ render(form.first_name) }}
      {{ render(form.last_name) }}
      {{ render(form.addr_1) }}
      {{ render(form.addr_2) }}
      {{ render(form.city) }}
      {{ render(form.state) }}
      {{ render(form.zip_code) }}
      {{ render(form.phone_h) }}
      {{ render(form.phone_c) }}
      {{ render(form.phone_w) }}
      {{ render(form.email) }}
      {{ render(form.address_length, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Employment</legend>
      {{ render(form.employer) }} 
      {{ render(form.occupation) }} 
      {{ render(form.employment_type) }}
    </fieldset>
    <fieldset>
      <legend>Family</legend>
      Please select the relationship to you of all the adults in your household:
      <table class="family_subtable">
        <tr>
          <th>&nbsp;</th>
          <th>Relation</th>
          <th>Name</th>
        </tr>
        {% for relation, name in [(form.relation1, form.name1), (form.relation2, form.name2),
                                  (form.relation3, form.name3), (form.relation4, form.name4),
                                  (form.relation5, form.name5)] %}
        <tr>
          <td>{{ loop.index }}. </td>
          <td>{{ relation() }}</td>
          <td>{{ name() }}</td>
        </tr>
        {% endfor %}
      </table>      
      {{ render(form.kids, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Veterinarian Reference</legend>
      If you currently own or have owned a pet in the past five years, please
      provide your veterinarian's name, address, and telephone number.<br />
      {{ render(form.ref1_firstname) }}
      {{ render(form.ref1_lastname) }}
      {{ render(form.ref1_address1) }}
      {{ render(form.ref1_address2) }}
      {{ render(form.ref1_city) }}
      {{ render(form.ref1_state) }}
      {{ render(form.ref1_zip) }}
      {{ render(form.ref1_phone) }}
    </fieldset>
    <fieldset>
      <legend>Pets</legend>
      <table class="pets_subtable">
        <tr>
          <th>&nbsp;</th>
          <th><span class="definition" title="Cat / Dog / Bird / Etc">Type</span></th>
          <th>Sex</th>
          <th>Age</th>
          <th>Spayed /<br />Neutered?</th>
          <th>Name</th>
          <th>If no longer owned, what happened?</th>
        </tr>
        {% for type, sex, age, name, altered, what in [(form.pet_1_species, form.pet_1_sex, form.pet_1_age, form.pet_1_name, form.pet_1_altered, form.pet_1_whathappened),
                                                       (form.pet_2_species, form.pet_2_sex, form.pet_2_age, form.pet_2_name, form.pet_2_altered, form.pet_2_whathappened), 
                                                       (form.pet_3_species, form.pet_3_sex, form.pet_3_age, form.pet_3_name, form.pet_3_altered, form.pet_3_whathappened), 
                                                       (form.pet_4_species, form.pet_4_sex, form.pet_4_age, form.pet_4_name, form.pet_4_altered, form.pet_4_whathappened), 
                                                       (form.pet_5_species, form.pet_5_sex, form.pet_5_age, form.pet_5_name, form.pet_5_altered, form.pet_5_whathappened)] %}
        <tr>
          <td>{{ loop.index }}.  </td>
          <td>{{ type() }}</td>
          <td>{{ sex() }}</td>
          <td>{{ age() }}</td>
          <td>{{ altered() }}</td>
          <td>{{ name() }}</td>
          <td>{{ what() }}</td>
        </tr>
        {% endfor %}
      </table>
    </fieldset>
    <fieldset>
      <legend>Pet Care</legend>
      {{ render(form.freefeed, colon=False) }}
      {{ render(form.whocares, colon=False) }}
      {{ render(form.home, colon=False) }}
      {{ render(form.needs, colon=False) }}
      {{ render(form.alonetime, colon=False) }}
      {{ render(form.dogkepthome) }}
      {{ render(form.dogkeptaway) }}
      {{ render(form.dogdoor, colon=False) }}
      {{ render(form.transport, colon=False) }}
      {{ render(form.crate, colon=False) }}
      {{ render(form.sleep, colon=False) }}
      {{ render(form.whyridgebacks, colon=False) }}
      {{ render(form.before, colon=False) }}
      {{ render(form.expenses, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>A Day In The Life...</legend>
      {{ render(form.dayinthelife) }}
      {{ render(form.dogasfamily, colon=False) }}
      {{ render(form.activitylevel) }}
      {{ render(form.awaycare, colon=False) }}
      {{ render(form.giveup, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Housing</legend>
      {{ render(form.housing, colon=False) }}
      {{ render(form.ownrent, colon=False) }}
      {{ render(form.landlordproof, colon=False) }}
      {{ render(form.yard, colon=False) }}
      {{ render(form.fence, colon=False) }}
      {{ render(form.fencedetails, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Ridgeback Preferences</legend>
      {{ render(form.ridgebackname, colon=False) }}
      {{ render(form.ridgebackgender, colon=False) }}
      {{ render(form.ridgebackage) }}
      {{ render(form.ridgebackridges, colon=False) }}
      {{ render(form.ridgebackpurebred, colon=False) }}
      {{ render(form.ridgebackhealthproblems, colon=False) }}
      {{ render(form.ridgebacksocialproblems, colon=False) }}
    </fieldset>
  </form>
{% endif %}
{% endblock %}