crrr/dogs/models/__init__.py
from dog import Dog
from picture import Picture

crrr/dogs/models/dog.py
from crrr import db
from crrr.dogs import constants as DOG


class Dog(db.Model):
    __tablename__ = 'dog'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    status = db.Column(db.SmallInteger)
    breed = db.Column(db.String())
    sex = db.Column(db.SmallInteger)
    age = db.Column(db.SmallInteger)
    mix = db.Column(db.Boolean())
    size = db.Column(db.SmallInteger)
    fee = db.Column(db.Integer)
    description = db.Column(db.Text())
    special_needs = db.Column(db.Boolean())
    home_without_dogs = db.Column(db.Boolean())
    home_without_cats = db.Column(db.Boolean())
    home_without_kids = db.Column(db.Boolean())
    fixed = db.Column(db.Boolean())
    shots = db.Column(db.Boolean())
    housetrained = db.Column(db.Boolean())
    archive = db.Column(db.Boolean(), default=False)
    happy_tails = db.Column(db.Text())

    # relations
    pictures = db.relationship('Picture')

    def __repr__(self):
        return '<Dog %r: adopted=%s>' % (self.name, self.getStatus())

    def getStatus(self):
        return DOG.STATUS[self.status]

    def setStatus(self, status):
        self.status = [k for k,v in DOG.STATUS.items() if v==status][0]

    def getSex(self):
        return DOG.SEX[self.sex]

    def setSex(self, sex):
        self.sex = [k for k,v in DOG.SEX.items() if v==sex][0]

    def getSize(self):
        return DOG.SIZE[self.size]

    def setSize(self, size):
        self.size = [k for k,v in DOG.SIZE.items() if v==size][0]

    def getAge(self):
        return DOG.AGE[self.age]

    def setAge(self, age):
        self.age = [k for k,v in DOG.AGE.items() if v==age][0]

crrr/dogs/models/picture.py
from werkzeug.security import generate_password_hash, check_password_hash
from crrr import db

class Picture(db.Model):
    __tablename__ = 'picture'

    id = db.Column(db.Integer, primary_key=True)
    dog_id = db.Column(db.Integer, db.ForeignKey('dog.id'))
    file_url = db.Column(db.String(), nullable=False)
    thumb_url = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return "<Picture %s>" % (self.file_url)

crrr/dogs/forms.py
# from crrr import uploaded_photos, app
from werkzeug.datastructures import FileStorage
from crrr.dogs import constants as DOG
from flask.ext.uploads import UploadSet, IMAGES
from flask.ext.wtf import Form
from flask.ext.wtf.file import FileAllowed, FileField
from wtforms import (
    IntegerField,
    TextField,
    SelectField,
    BooleanField,
    SubmitField,
    FieldList,
    TextAreaField,
    validators
)

images = UploadSet('images', IMAGES)


class DogMixin(Form):
    name = TextField('Name', [validators.Required('A name is required.')])
    breed = TextField('Breed')
    sex = SelectField('Sex', choices=[(str(key), val.capitalize()) for key, val in DOG.SEX.iteritems()])
    status = SelectField('Status', choices=[(str(key), val.capitalize()) for key, val in DOG.STATUS.iteritems()])
    age = SelectField('Age', choices=[(str(key), val.capitalize()) for key, val in DOG.AGE.iteritems()])
    mix = SelectField('Mixed Breed?', choices=[('0', 'N'), ('1', 'Y')])
    size = SelectField('Size (when grown)', choices=[(str(key), val.capitalize()) for key, val in DOG.SIZE.iteritems()])
    fee = IntegerField('Fee', [validators.Optional()])
    description = TextAreaField('Description')
    special_needs = BooleanField('Special Needs')
    home_without_dogs = BooleanField('Home without dogs')
    home_without_cats = BooleanField('Home without cats')
    home_without_kids = BooleanField('Home without children')
    fixed = BooleanField('Spayed / Neutered')
    shots = BooleanField('Up to date with shots')
    housetrained = BooleanField('Housetrained')

    uploads = FieldList(
        FileField('Picture', validators=[FileAllowed(images, 'Images only!')]),
        min_entries=3
    )


class AddDog(DogMixin):
    send = SubmitField('Add Dog')


class EditDog(DogMixin):
    happy_tails = TextAreaField('Happy Tails')
    archive = BooleanField('Archive')
    send = SubmitField('Update Dog')

    def __init__(self, *args, **kwargs):
        DogMixin.__init__(self, *args, **kwargs)
        if "obj" in kwargs:
            dog = kwargs['obj']
            self.id = dog.id
            for i, picture in enumerate(dog.pictures):
                self.uploads.entries[i].data = FileStorage(filename=picture.thumb_url)

crrr/dogs/views.py
import os
from PIL import Image
from flask import render_template, flash, g, url_for, redirect, Blueprint, request
from flask.ext.login import login_required
from crrr import app, db, uploaded_photos
from crrr.dogs.models import Dog, Picture
from crrr.dogs import constants as DOG
from crrr.dogs.forms import AddDog, EditDog

mod = Blueprint('dogs', __name__, url_prefix='/dogs')

# Thumbnails
THUMB_SIZE = (750, 750)
THUMB_PREFIX = "tb_"

# PAGINATION
PER_PAGE = 20


@mod.route('/')
@login_required
def index():
    g.title = 'CRRR - Dogs'
    dogs = Dog.query.all()
    return render_template('dogs/index.html', dogs=dogs)


@mod.route('/available/')
def available():
    g.available_dogs = True
    g.title = "CRRR - Available Dogs"
    dogs = Dog.query.filter(Dog.status == DOG.ADOPTABLE).order_by(Dog.name).all()
    return render_template('dogs/available.html', dogs=dogs)


@mod.route('/happy_tails/', defaults={'page': 1})
@mod.route('/happy_tails/page/<int:page>')
def happy_tails(page):
    g.happy_tails = True
    g.title = "CRRR - Happy Tails"
    pagination = Dog.query.filter(Dog.happy_tails != None).filter(Dog.status == DOG.ADOPTED).order_by(Dog.name).paginate(page, PER_PAGE)  # noqa
    return render_template('dogs/happy_tails.html', dogs=pagination.items, pagination=pagination, page=page)


@mod.route('/<int:id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(id):
    g.title = 'CRRR - Edit Dog'
    dog = Dog.query.filter_by(id=id).first_or_404()
    form = EditDog() if request.method == 'POST' else EditDog(obj=dog)
    if form.validate_on_submit():
        form.populate_obj(dog)
        for i, picture in enumerate(form.uploads):

            # Nothing was actually uploaded for this image
            if not picture.data:
                continue

            app.logger.debug('processing picture: %s', picture)
            # If the picture already exists, delete it
            try:
                p = dog.pictures[i]
            except IndexError:
                p = Picture()
                dog.pictures.append(p)

            # Save the file original file
            filename = uploaded_photos.save(picture.data, folder=str(dog.id))

            # Create a thumbnail of this new picture
            thumb = thumbify(uploaded_photos.path(filename))
            p.file_url = os.path.basename(filename)
            p.thumb_url = os.path.basename(thumb)

        db.session.add(dog)
        db.session.commit()
        flash("%s was successfully edited." % dog.name)
        return redirect(url_for('admin.index'))

    return render_template('dogs/edit.html', form=form)


@mod.route('/add/', methods=['GET', 'POST'])
@login_required
def add():
    form = AddDog()

    if form.validate_on_submit():
        dog = Dog()
        db.session.add(dog)
        db.session.flush()  # So we can get the ID value
        form.populate_obj(dog)

        pictures = [p for p in form.uploads.entries if p]
        for picture in pictures:
            if not picture.data:
                continue
            app.logger.debug('adding picture: %s', picture)
            # Save the file original file
            filename = uploaded_photos.save(picture.data, folder=str(dog.id))

            # Create the thumbnail
            thumb = thumbify(uploaded_photos.path(filename))
            p = Picture(file_url=os.path.basename(filename),
                        thumb_url=os.path.basename(thumb))
            dog.pictures.append(p)

        db.session.commit()
        flash("%s was successfully added." % dog.name)
        return redirect(url_for('admin.index'))

    return render_template('dogs/add.html', form=form)


def thumbify(infile):
    out_filename = os.path.join(os.path.dirname(infile), THUMB_PREFIX + os.path.basename(infile))
    img = Image.open(infile)
    img.thumbnail(THUMB_SIZE, Image.ANTIALIAS)
    img.save(out_filename)
    return out_filename

crrr/root/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import render_template, g, Blueprint
from flask.ext.mail import Message
from flask.ext.login import current_user
from crrr import app, mail
from crrr.root.forms import (
    Volunteer,
)

mod = Blueprint('root', __name__, url_prefix='/')


@mod.route('/')
def index():
    g.index = True
    return render_template('root/index.html')


@mod.route('about/')
def about():
    g.about = True
    g.title = "CRRR - About"
    return render_template('root/about.html')


@mod.route('breed/')
def breed():
    g.breed = True
    g.title = "CRRR - Breed"
    return render_template('root/breed.html')


@mod.route('faq/')
def faq():
    g.faq = True
    g.title = "CRRR - FAQ"
    return render_template('root/faq.html')


@mod.route('volunteer/', methods=['GET', 'POST'])
def volunteer():
    g.volunteer = True
    g.title = "CRRR - Volunteer"
    form = Volunteer()
    if form.validate_on_submit():
        submitted_at = datetime.now().strftime("%B %d, %Y, %I:%M %p")
        app.logger.info('Volunteer application submitted.')
        app.logger.debug(form.data)
        subject = '{} {} Volunteer Application Submittal'.format(
            form.first_name.data, form.last_name.data
        )
        sender = app.config.get('CRRR_EMAIL')
        msg = Message(subject,
                      sender=sender,
                      recipients=[sender, form.email.data],
                      html=render_template('root/email_volunteer.html',
                                           form=form,
                                           submitted_at=submitted_at)
                      )
        mail.send(msg)
        return render_template('root/volunteer.html')
    return render_template('root/volunteer.html', form=form)


@app.errorhandler(404)
def page_not_found(error):
    return render_template('page_not_found.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('internal_server_error.html'), 404


@app.before_request
def before_request():
    g.user = current_user

crrr/templates/dogs/add.html
{% extends "layout.html" %}
{% block content %}
{% from "_helpers.html" import render, bool_render %}
<div class="header">
  <h1 class="content-subhead">Add A Dog</h1>
</div>
<form method="POST" action={{ url_for('dogs.add') }} class="pure-form pure-form-aligned" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    {% if form.errors %}
    <p class="missing">Please address the following errors:</p>
    <ul class="missing">
      {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
          <li>{{ form[field_name].label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
    {% endif %}

    <fieldset>
        {{ render(form.name) }}
        {{ render(form.breed, value="Rhodesian Ridgeback") }}
        {{ render(form.sex) }}
        {{ render(form.status) }}
        {{ render(form.age) }}
        {{ render(form.mix) }}
        {{ render(form.size) }}
        {{ render(form.fee) }}
        {{ render(form.description, rows="10", class="pure-input-1-2") }}
    </fieldset>
    <fieldset>
        Check all that apply:<br />
        {{ bool_render(form.special_needs) }}
        {{ bool_render(form.home_without_dogs) }}
        {{ bool_render(form.home_without_cats) }}
        {{ bool_render(form.home_without_kids) }}
        {{ bool_render(form.fixed) }}
        {{ bool_render(form.shots) }}
        {{ bool_render(form.housetrained) }}
    </fieldset>
    <fieldset>
    {% for picture in form.uploads.entries %}
        <div class="pure-control-group">
            {{ picture.label(text="Picture "+loop.index|string+":") }}
            {{ picture }}
        </div>
    {% endfor %}
    </fieldset>
    <div class="pure-controls">{{ form.send(class="pure-button pure-button-primary") }}</div>
</form>
{% endblock %}

crrr/templates/dogs/available.html
{% extends "layout.html" %}
{% block content %}
{% if dogs %}
  {% for dog in dogs %}
    <div class="header">
      <h1 class="content-subhead avail-dog-name">{{ dog.name }}</h1>
    </div>
    <div class="avail-dog">
      <div id="image-container" class="image-container" style="overflow:hidden;">
        {% for picture in dog.pictures %}
          <div class="happy-tails-pic" style="background-image:url({{ url_for('static', filename='images/'+dog.id|string+'/'+picture.thumb_url) }});">
            <img src={{ url_for('static', filename='images/'+dog.id|string+'/'+picture.thumb_url) }} style="display:none;"/>
          </div>
        {% endfor %}
      </div>
      <div class="pure-g-r">
      <div class="l-box pure-g-r avail-dog-desc">
        <div class="pure-u-1-8 avail-dog-info">
          <strong>Size:</strong>  {{ dog.getSize() }}<br />
          <strong>Age:</strong>  {{ dog.getAge() }} <br />
          <strong>Sex:</strong>  {{ dog.getSex()|capitalize }}<br />
          <strong>Mix:</strong>  {% if dog.mix %}Y{% else %}N{% endif %}<br />
          {% if dog.fee %}<strong>Fee:</strong>  ${{ dog.fee }}<br />{% endif %}
        </div>
        <div class="pure-u-5-24 avail-dog-info">
          <ul class="fa-ul">
              {% if dog.shots %}<li><i class="fa-li fa fa-check"></i>Up to date on routine shots</li>{% endif %}
              {% if dog.housetrained %}<li><i class="fa-li fa fa-check"></i>Housetrained</li>{% endif %}
              {% if dog.fixed %}<li><i class="fa-li fa fa-check"></i>{% if dog.getSex() == "male" %}Neutered{% else %}Spayed{% endif %}</li>{% endif %}
              {% if dog.special_needs %}<li><i class="fa-li fa fa-check"></i>A special needs animal</li>{% endif %}
              {% if dog.home_without_dogs %}<li><i class="fa-li fa fa-check"></i>In need of a home without other dogs</li>{% endif %}
              {% if dog.home_without_cats %}<li><i class="fa-li fa fa-check"></i>In need of a home without cats</li>{% endif %}
              {% if dog.home_without_kids %}<li><i class="fa-li fa fa-check"></i>In need of a home without children</li>{% endif %}
          </ul>
        </div>
        <div class="pure-u-2-3">
          {{ dog.description|replace('\r','')|replace('\\n','')|trim }}
        </div>
        </div> <!-- pure-g-r -->
      </div> <!-- avail-dog-desc -->
    </div> <!-- avail-dog -->
  {% endfor %}


{% else %}
<p>Bummer!  There are presently no dogs available for adoption.  Please check back
soon!</p>
{% endif %}
{% endblock %}

{% block end_of_page %}
  {{ super() }}

  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" src={{ url_for('static', filename='js/plugins.js') }}></script>
  <script type="text/javascript" src={{ url_for('static', filename='js/main.js') }}></script>
  <script type="text/javascript" src={{ url_for('static', filename='js/linear_partition.js') }}></script>
  <script type="text/javascript" src={{ url_for('static', filename='js/avail_resize.js') }}></script>
  <script type="text/javascript">
  try{jQuery.ready();}catch(e){}
  </script>

{% endblock %}

crrr/templates/dogs/edit.html
{% extends "layout.html" %}
{% block content %}
{% from "_helpers.html" import render, bool_render %}
<div class="header">
  <h1 class="content-subhead">Edit A Dog</h1>
</div>
{% if form.errors %}
{% for field_name, field_errors in form.errors|dictsort if field_errors %}
  {% for error in field_errors %}
  <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ form[field_name].label(style="display: inline;") }}:  {{ error }}
  </div>
  {% endfor %}
{% endfor %}
{% endif %}
<form method="POST" action="" class="pure-form pure-form-aligned" enctype="multipart/form-data">
    <div>{{ form.hidden_tag() }}</div>
    <fieldset>
        {{ render(form.name) }}
        {{ render(form.breed) }}
        {{ render(form.sex) }}
        {{ render(form.status) }}
        {{ render(form.age) }}
        {{ render(form.mix) }}
        {{ render(form.size) }}
        {{ render(form.fee) }}
        {{ render(form.description, rows="10", class="pure-input-1-2") }}
    </fieldset>

    <fieldset>
        {{ bool_render(form.special_needs) }}
        {{ bool_render(form.home_without_dogs) }}
        {{ bool_render(form.home_without_cats) }}
        {{ bool_render(form.home_without_kids) }}
        {{ bool_render(form.fixed) }}
        {{ bool_render(form.shots) }}
        {{ bool_render(form.housetrained) }}
    </fieldset>
    <fieldset>
    {% for picture in form.uploads.entries %}
        <div class="pure-control-group">
            {{ picture.label(text="Picture "+loop.index|string+":") }}
            {{ picture }}
        </div>
        {% if picture.data %}
        <div class="pure-control-group"><label>Currently:</label>
            <img src={{ url_for('static', filename='images/' + form.id|string + '/' + picture.data.filename) }}>
            </div>
        {% endif %}
    {% endfor %}
    </fieldset>

    <fieldset>
        {{ render(form.happy_tails, rows="10", class="pure-input-1-2") }}
        {{ bool_render(form.archive) }}
    </fieldset>
    <div class="pure-controls">{{ form.send(label="Edit Dog", class="pure-button pure-button-primary") }}</div>
</form>
{% endblock %}

crrr/templates/dogs/happy_tails.html
{% extends "layout.html" %}
{% from "_helpers.html" import render_pagination %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='modal.css') }}">
{% endblock %}
{% block content %}
{% if page == 1 %}<h1>Happy Tails Tales</h1>{% endif %}
{% if dogs %}
{% if page == 1 %}
<p>Thanks to volunteers, adopters, and those who've donated to CRRR, we've been fortunate over the years to rescue many dogs.  We're proud to present their stories!  Should any of them move you, consider <a href={{ url_for('application.apply') }}>adopting</a> or <a href={{ url_for('root.volunteer') }}>volunteering</a>.</p>
{% endif %}
  <div id="image-container" style="overflow:hidden;">
    {% for dog in dogs %}
      {% if dog.pictures %}
        {% set modalID = 'modal' + loop.index|string %}
        <div class="happy-tails-container"><a href="#{{ modalID }}" role="button" data-toggle="modal" data-target="#{{ modalID }}">
          <div class="happy-tails-pic" style="background-image:url({{ url_for('static', filename='images/'+dog.id|string+'/'+dog.pictures[0].file_url) }});">
            <img src={{ url_for('static', filename='images/'+dog.id|string+'/'+dog.pictures[0].file_url) }} style="display:none;"/>
          </div>
          <div class="happy-tails-txt">
            <p>{{ dog.name }}</p>
          </div>
          </a>
          <div id="{{ modalID }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="{{ modalID }}" aria-hidden="true">
            <div class="modal-header">
              <h1 id="{{ modalID }}">{{ dog.name }}</h1>
            </div>
            <div class="modal-body">
              <p>{{ dog.happy_tails|replace('\r','')|replace('\\n','')|trim }}</p>
            </div></a>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div> <!-- image-container -->
{{ render_pagination(pagination) }}
{% else %}
{% if page == 1 %}
<p>There are plenty of happy tales (tails?) to tell, we just haven't gotten
around to it yet.  Please check back soon!</p>
{% endif %}
{% endif %}
{% endblock %}

{% block end_of_page %}
  {{ super() }}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src={{ url_for('static', filename='js/plugins.js') }}></script>
  <script src={{ url_for('static', filename='js/main.js') }}></script>
  <script src={{ url_for('static', filename='js/linear_partition.js') }}></script>
  <script src={{ url_for('static', filename='js/resize.js') }}></script>
  <script src={{ url_for('static', filename='js/hovering.js') }}></script>
  <script src="https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
{% endblock %}

crrr/templates/dogs/index.html
{% extends "layout.html" %}
{% block content %}
{% if dogs %}
  <table class="pure-table pure-table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Breed</th>
        <th>Age</th>
        <th>Sex</th>
        <th>Status</th>
        <th>Archived</th>
      </tr>
    </thead>
    <tbody>
    {% for dog in dogs %}
      <tr>
        <td>{{ dog.name }}</td>
        <td>{{ dog.breed }}</td>
        <td>{{ dog.getAge() }}</td>
        <td>{{ dog.getSex() }}</td>
        <td>{{ dog.getStatus() }}</td>
        <td>{{ dog.archive }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
<p>No dogs present yet!  Go <a href={{ url_for('dogs.add') }}>add</a> some!</p>
{% endif %}
{% endblock %}