crrr/root/models/__init__.py
from application import App
from volunteer import Volunteer

crrr/root/models/app.py
from crrr import db
from datetime import datetime

class Status(object):
    NEW          = 'new'
    INIT         = 'initial contact made'
    ARRANGE_HC   = 'arranging hc'
    HC_COMPLETED = 'hc completed'
    APPROVED     = 'approved'
    UNAPPROVED   = 'unapproved'


class App(db.Model):
    __tablename__ = 'app'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    dog_id = db.Column(db.Integer, db.ForeignKey('dog.id'))
    assignee_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    submittal_date = db.Column(db.DateTime, default=datetime.now)
    status = db.Column(db.Enum(Status.NEW,
                               Status.INIT,
                               Status.ARRANGE_HC,
                               Status.HC_COMPLETED,
                               Status.APPROVED,
                               Status.UNAPPROVED,
                               name='app_status'),
                               default=Status.NEW)
    archive = db.Column(db.Boolean, default=False)

    # relationships
    applicant = db.relationship('User', foreign_keys=[user_id], backref='apps',
                                uselist=False)
    assignee  = db.relationship('User', foreign_keys=[assignee_id],
                                uselist=False)
    dog = db.relationship('Dog', backref='apps', uselist=False)


    def __repr__(self):
        return "<App for %s is %s>" % (self.dog, self.status)

crrr/root/models/application.py
from crrr import db
from datetime import datetime


class Status(object):
    NEW = 'new'
    INIT = 'initial contact made'
    ARRANGE_HC = 'arranging hc'
    HC_COMPLETED = 'hc completed'
    APPROVED = 'approved'
    UNAPPROVED = 'unapproved'


class App(db.Model):
    __tablename__ = 'app'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    dog_id = db.Column(db.Integer, db.ForeignKey('dog.id'))
    assignee_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    submittal_date = db.Column(db.DateTime, default=datetime.now)
    status = db.Column(db.Enum(Status.NEW,
                               Status.INIT,
                               Status.ARRANGE_HC,
                               Status.HC_COMPLETED,
                               Status.APPROVED,
                               Status.UNAPPROVED,
                               name='app_status'),
                       default=Status.NEW)
    archive = db.Column(db.Boolean, default=False)

    # relationships
    applicant = db.relationship('User', foreign_keys=[user_id], backref='apps',
                                uselist=False)
    assignee = db.relationship('User', foreign_keys=[assignee_id],
                               uselist=False)
    dog = db.relationship('Dog', backref='apps', uselist=False)

    def __repr__(self):
        return "<App for %s is %s>" % (self.dog, self.status)

crrr/root/models/volunteer.py
from crrr import db


class Volunteer(db.Model):
    __tablename__ = 'volunteer'

    id = db.Column(db.Integer, primary_key=True)

    first_name = db.Column(db.String(), nullable=False)
    last_name = db.Column(db.String(), nullable=False)
    address_id = db.Column(db.Integer, db.ForeignKey('address.id'))

    email = db.Column(db.String(), nullable=False)

    foster_fam = db.Column(db.Boolean)
    transport = db.Column(db.Boolean)
    home_check = db.Column(db.Boolean)
    ref_check = db.Column(db.Boolean)
    crate = db.Column(db.Boolean)
    supplies = db.Column(db.Boolean)

    # relationships
    phones = db.relationship('Phone')

crrr/admin/views.py
import string
import random
from datetime import (
    timedelta,
    datetime
)
from flask import request, render_template, flash, g, url_for, redirect, Blueprint, abort
from flask.ext.mail import Message
from flask.ext.login import login_required, login_user, logout_user
from crrr import mail, login_manager, db, app
from crrr.dogs.models import Dog
from crrr.admin.models import User, Confirm, Reset
from crrr.admin.forms import (
    CreateUser,
    ResetPassword,
    Email,
    Login,
)


mod = Blueprint('admin', __name__, url_prefix='/admin')


@mod.route('/')
@login_required
def index():
    g.title = "CRRR - Admin"
    show_archived_dogs = request.args.get('showarchiveddogs')
    if show_archived_dogs:
        dogs = Dog.query.order_by(Dog.name).all()
    else:
        dogs = Dog.query.filter_by(archive=False).order_by(Dog.name).all()
    return render_template('admin/index.html', dogs=dogs)


def create_hash():
    return ''.join(random.choice(string.ascii_letters + string.digits) for x in range(32))


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    form = CreateUser()
    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.email = form.email.data
        user.set_password(form.password.data)
        # Now the confirmation hash associated with this user
        hash = create_hash()
        confirm = Confirm(hash=hash)
        user.confirmation = confirm
        db.session.add(user)
        db.session.commit()
        # Send an email with confirmation link
        msg = Message('Your CRRR account has been created!',
                      sender='info@crrr.org',
                      recipients=[user.email])
        msg.body = 'Please visit %s to complete your account registration.' % (url_for('user.confirm', hash=hash, _external=True))
        mail.send(msg)
        flash('A confirmation email has been sent your way.')
        return redirect(url_for("user.login"))
    else:
        return render_template('admin/register.html', form=form)


@mod.route('/confirm/<hash>')
def confirm(hash):
    assert False
    result = db.session.query(Confirm, User).\
        join(User).\
        filter(Confirm.hash == hash).\
        first()
    if result is None:
        abort(404)

    confirm, user = result
    user.active = True
    db.session.delete(confirm)
    db.session.flush()
    db.session.commit()
    return render_template('admin/confirm.html', user=user)


@mod.route('/reset/<hash>/', methods=['GET', 'POST'])
def reset_hash(hash):
    result = db.session.query(User, Reset).\
        join(Reset).\
        filter(Reset.hash == hash).\
        first()
    print result
    if result is None:
        abort(404)

    form = ResetPassword()
    if form.validate_on_submit():

        # They exist!
        user, reset = result

        # The user has an hour to reset their password
        allowable_delta = timedelta(hours=1)
        actual_delta = datetime.utcnow() - reset.timestamp
        if actual_delta > allowable_delta:
            db.session.delete(reset)
            db.session.commit()
            return 'Too slow!'

        user, reset = result
        user.set_password(form.password.data)
        db.session.delete(reset)
        db.session.commit()
        flash('Your password was successfully reset.')
        login = Login()
        return render_template('admin/login.html', form=login)
    else:
        return render_template('admin/reset_hash.html', form=form)


@mod.route('/reset/', methods=['GET', 'POST'])
def reset():
    form = Email()
    if form.validate_on_submit():
        reset = Reset(hash=create_hash(),
                      user_id=form.user.id)
        user = User.query.get(form.user.id)
        subject = 'CRRR Password Reset'
        sender = app.config.get('CRRR_EMAIL')
        msg = Message(subject,
                      sender=sender,
                      recipients=[user.email],
                      html=render_template('root/reset_password_email.html',
                                           reset=reset)
                      )
        mail.send(msg)

        db.session.add(reset)
        db.session.commit()
        flash('An email has been sent with instructions for resetting your password.')
        return render_template('root/index.html')
    else:
        return render_template('admin/reset.html', form=form)


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    g.title = 'CRRR - Login'
    g.login = True
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        login_user(user, remember=form.remember_me.data)
        flash('You have logged in.')
        return redirect(request.args.get("next") or url_for("admin.index"))
    return render_template('admin/login.html', form=form)


@mod.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('root.index'))


@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

crrr/dogs/views.py
import os
from PIL import Image
from flask import render_template, flash, g, url_for, redirect, Blueprint, request
from flask.ext.login import login_required
from crrr import app, db, uploaded_photos
from crrr.dogs.models import Dog, Picture
from crrr.dogs import constants as DOG
from crrr.dogs.forms import AddDog, EditDog

mod = Blueprint('dogs', __name__, url_prefix='/dogs')

# Thumbnails
THUMB_SIZE = (750, 750)
THUMB_PREFIX = "tb_"

# PAGINATION
PER_PAGE = 20


@mod.route('/')
@login_required
def index():
    g.title = 'CRRR - Dogs'
    dogs = Dog.query.all()
    return render_template('dogs/index.html', dogs=dogs)


@mod.route('/available/')
def available():
    g.available_dogs = True
    g.title = "CRRR - Available Dogs"
    dogs = Dog.query.filter(Dog.status == DOG.ADOPTABLE).order_by(Dog.name).all()
    return render_template('dogs/available.html', dogs=dogs)


@mod.route('/happy_tails/', defaults={'page': 1})
@mod.route('/happy_tails/page/<int:page>')
def happy_tails(page):
    g.happy_tails = True
    g.title = "CRRR - Happy Tails"
    pagination = Dog.query.filter(Dog.happy_tails != None).filter(Dog.status == DOG.ADOPTED).order_by(Dog.name).paginate(page, PER_PAGE)  # noqa
    return render_template('dogs/happy_tails.html', dogs=pagination.items, pagination=pagination, page=page)


@mod.route('/<int:id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(id):
    g.title = 'CRRR - Edit Dog'
    dog = Dog.query.filter_by(id=id).first_or_404()
    form = EditDog() if request.method == 'POST' else EditDog(obj=dog)
    if form.validate_on_submit():
        form.populate_obj(dog)
        for i, picture in enumerate(form.uploads):

            # Nothing was actually uploaded for this image
            if not picture.data:
                continue

            app.logger.debug('processing picture: %s', picture)
            # If the picture already exists, delete it
            try:
                p = dog.pictures[i]
            except IndexError:
                p = Picture()
                dog.pictures.append(p)

            # Save the file original file
            filename = uploaded_photos.save(picture.data, folder=str(dog.id))

            # Create a thumbnail of this new picture
            thumb = thumbify(uploaded_photos.path(filename))
            p.file_url = os.path.basename(filename)
            p.thumb_url = os.path.basename(thumb)

        db.session.add(dog)
        db.session.commit()
        flash("%s was successfully edited." % dog.name)
        return redirect(url_for('admin.index'))

    return render_template('dogs/edit.html', form=form)


@mod.route('/add/', methods=['GET', 'POST'])
@login_required
def add():
    form = AddDog()

    if form.validate_on_submit():
        dog = Dog()
        db.session.add(dog)
        db.session.flush()  # So we can get the ID value
        form.populate_obj(dog)

        pictures = [p for p in form.uploads.entries if p]
        for picture in pictures:
            if not picture.data:
                continue
            app.logger.debug('adding picture: %s', picture)
            # Save the file original file
            filename = uploaded_photos.save(picture.data, folder=str(dog.id))

            # Create the thumbnail
            thumb = thumbify(uploaded_photos.path(filename))
            p = Picture(file_url=os.path.basename(filename),
                        thumb_url=os.path.basename(thumb))
            dog.pictures.append(p)

        db.session.commit()
        flash("%s was successfully added." % dog.name)
        return redirect(url_for('admin.index'))

    return render_template('dogs/add.html', form=form)


def thumbify(infile):
    out_filename = os.path.join(os.path.dirname(infile), THUMB_PREFIX + os.path.basename(infile))
    img = Image.open(infile)
    img.thumbnail(THUMB_SIZE, Image.ANTIALIAS)
    img.save(out_filename)
    return out_filename

crrr/root/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import render_template, g, Blueprint
from flask.ext.mail import Message
from flask.ext.login import current_user
from crrr import app, mail
from crrr.root.forms import (
    Volunteer,
)

mod = Blueprint('root', __name__, url_prefix='/')


@mod.route('/')
def index():
    g.index = True
    return render_template('root/index.html')


@mod.route('about/')
def about():
    g.about = True
    g.title = "CRRR - About"
    return render_template('root/about.html')


@mod.route('breed/')
def breed():
    g.breed = True
    g.title = "CRRR - Breed"
    return render_template('root/breed.html')


@mod.route('faq/')
def faq():
    g.faq = True
    g.title = "CRRR - FAQ"
    return render_template('root/faq.html')


@mod.route('volunteer/', methods=['GET', 'POST'])
def volunteer():
    g.volunteer = True
    g.title = "CRRR - Volunteer"
    form = Volunteer()
    if form.validate_on_submit():
        submitted_at = datetime.now().strftime("%B %d, %Y, %I:%M %p")
        app.logger.info('Volunteer application submitted.')
        app.logger.debug(form.data)
        subject = '{} {} Volunteer Application Submittal'.format(
            form.first_name.data, form.last_name.data
        )
        sender = app.config.get('CRRR_EMAIL')
        msg = Message(subject,
                      sender=sender,
                      recipients=[sender, form.email.data],
                      html=render_template('root/email_volunteer.html',
                                           form=form,
                                           submitted_at=submitted_at)
                      )
        mail.send(msg)
        return render_template('root/volunteer.html')
    return render_template('root/volunteer.html', form=form)


@app.errorhandler(404)
def page_not_found(error):
    return render_template('page_not_found.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('internal_server_error.html'), 404


@app.before_request
def before_request():
    g.user = current_user

crrr/templates/root/about.html
{% extends "layout.html" %}
{% block content %}
<h1>CRRR</h1>
<p>We've been around in various forms since 1993.  Over the years, there have been many people who have contributed in one way or another to our success.  From coordinators to foster families to behavioral consultants, our volunteers have donated thousands of hours.</p>
<h1>Web</h1>
<p>Are you a web developer looking for ideas for your rescue website?  Here are some of the technologies we're using:</p>
<ul>
  <li>Python Web Framework:  <a href="http://flask.pocoo.org">Flask</a></li>
  <li>Source Code:  <a href="https://github.com/SirScott/crrr">GitHub</a></li>
  <li>Hosting:  <a href="https://www.digitalocean.com/?refcode=088c4dfd4c17">Digital Ocean</a></li>
</ul>
<p>Also, a big thanks to <a href="http://www.dykumos.com/">Asta McCormick</a> for graciously providing the banner artwork for this site!</p>
{% endblock %}

crrr/templates/root/application.html
{% extends "layout.html" %}
{% block content %}
{% from "_helpers.html" import render %}
{% if form %}
<h1>Adoption Application</h1>
<p>Congratulations!  You've taken the first step towards adopting your
Ridgeback by seeking out the application.  Please be sure to fill in all fields
denoted with red text as they are required.  Upon completion of the form, you
should be contacted by a Colorado Rhodesian Ridgeback Rescue representative
after your information has been reviewed.  (This can take a week, please be
patient!)  The next step in our process will be for a volunteer to arrange a
home visit.  (Don't panic, we aren't interested in your housekeeping, and we
don't care how big or little your house is!)  This is just an informal, short
visit to make sure the dog will be going to a safe place, and to chat about
what you are looking for in a dog.  That way we can help match the right dog
with the right home. </p>
  <form method="POST" action={{ url_for('application.apply') }} class="pure-form pure-form-aligned" id="application">
    {{ form.hidden_tag() }}
    {% if form.errors %}
    <p class="missing">Oh no!  Your application hasn't passed our validation!  Please ensure the following required fields are filled
in properly:</p>
    <ul class="missing">
      {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
          <li>{{ form[field_name].label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
      <legend>Personal Information</legend>
      {{ render(form.first_name) }}
      {{ render(form.last_name) }}
      {{ render(form.addr_1) }}
      {{ render(form.addr_2) }}
      {{ render(form.city) }}
      {{ render(form.state) }}
      {{ render(form.zip_code) }}
      {{ render(form.phone_h) }}
      {{ render(form.phone_c) }}
      {{ render(form.phone_w) }}
      {{ render(form.email) }}
      {{ render(form.address_length, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Employment</legend>
      {{ render(form.employer) }} 
      {{ render(form.occupation) }} 
      {{ render(form.employment_type) }}
    </fieldset>
    <fieldset>
      <legend>Family</legend>
      Please select the relationship to you of all the adults in your household:
      <table class="family_subtable">
        <tr>
          <th>&nbsp;</th>
          <th>Relation</th>
          <th>Name</th>
        </tr>
        {% for relation, name in [(form.relation1, form.name1), (form.relation2, form.name2),
                                  (form.relation3, form.name3), (form.relation4, form.name4),
                                  (form.relation5, form.name5)] %}
        <tr>
          <td>{{ loop.index }}. </td>
          <td>{{ relation() }}</td>
          <td>{{ name() }}</td>
        </tr>
        {% endfor %}
      </table>      
      {{ render(form.kids, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Veterinarian Reference</legend>
      If you currently own or have owned a pet in the past five years, please
      provide your veterinarian's name, address, and telephone number.<br />
      {{ render(form.ref1_firstname) }}
      {{ render(form.ref1_lastname) }}
      {{ render(form.ref1_address1) }}
      {{ render(form.ref1_address2) }}
      {{ render(form.ref1_city) }}
      {{ render(form.ref1_state) }}
      {{ render(form.ref1_zip) }}
      {{ render(form.ref1_phone) }}
    </fieldset>
    <fieldset>
      <legend>Pets</legend>
      <table class="pets_subtable">
        <tr>
          <th>&nbsp;</th>
          <th><span class="definition" title="Cat / Dog / Bird / Etc">Type</span></th>
          <th>Sex</th>
          <th>Age</th>
          <th>Spayed /<br />Neutered?</th>
          <th>Name</th>
          <th>If no longer owned, what happened?</th>
        </tr>
        {% for type, sex, age, name, altered, what in [(form.pet_1_species, form.pet_1_sex, form.pet_1_age, form.pet_1_name, form.pet_1_altered, form.pet_1_whathappened),
                                                       (form.pet_2_species, form.pet_2_sex, form.pet_2_age, form.pet_2_name, form.pet_2_altered, form.pet_2_whathappened), 
                                                       (form.pet_3_species, form.pet_3_sex, form.pet_3_age, form.pet_3_name, form.pet_3_altered, form.pet_3_whathappened), 
                                                       (form.pet_4_species, form.pet_4_sex, form.pet_4_age, form.pet_4_name, form.pet_4_altered, form.pet_4_whathappened), 
                                                       (form.pet_5_species, form.pet_5_sex, form.pet_5_age, form.pet_5_name, form.pet_5_altered, form.pet_5_whathappened)] %}
        <tr>
          <td>{{ loop.index }}.  </td>
          <td>{{ type() }}</td>
          <td>{{ sex() }}</td>
          <td>{{ age() }}</td>
          <td>{{ altered() }}</td>
          <td>{{ name() }}</td>
          <td>{{ what() }}</td>
        </tr>
        {% endfor %}
      </table>
    </fieldset>
    <fieldset>
      <legend>Pet Care</legend>
      {{ render(form.freefeed, colon=False) }}
      {{ render(form.whocares, colon=False) }}
      {{ render(form.home, colon=False) }}
      {{ render(form.needs, colon=False) }}
      {{ render(form.alonetime, colon=False) }}
      {{ render(form.dogkepthome) }}
      {{ render(form.dogkeptaway) }}
      {{ render(form.dogdoor, colon=False) }}
      {{ render(form.transport, colon=False) }}
      {{ render(form.crate, colon=False) }}
      {{ render(form.sleep, colon=False) }}
      {{ render(form.whyridgebacks, colon=False) }}
      {{ render(form.before, colon=False) }}
      {{ render(form.expenses, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>A Day In The Life...</legend>
      {{ render(form.dayinthelife) }}
      {{ render(form.dogasfamily, colon=False) }}
      {{ render(form.activitylevel) }}
      {{ render(form.awaycare, colon=False) }}
      {{ render(form.giveup, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Housing</legend>
      {{ render(form.housing, colon=False) }}
      {{ render(form.ownrent, colon=False) }}
      {{ render(form.landlordproof, colon=False) }}
      {{ render(form.yard, colon=False) }}
      {{ render(form.fence, colon=False) }}
      {{ render(form.fencedetails, colon=False) }}
    </fieldset>
    <fieldset>
      <legend>Ridgeback Preferences</legend>
      {{ render(form.ridgebackname, colon=False) }}
      {{ render(form.ridgebackgender, colon=False) }}
      {{ render(form.ridgebackage) }}
      {{ render(form.ridgebackridges, colon=False) }}
      {{ render(form.ridgebackpurebred, colon=False) }}
      {{ render(form.ridgebackhealthproblems, colon=False) }}
      {{ render(form.ridgebacksocialproblems, colon=False) }}
    </fieldset>
    <div class="pure-controls">{{ form.submit(class="pure-button pure-button-primary") }}</div>
  </form>
<p>If you have questions or need more info, please contact Inge Trump, CRRR coordinator:<br />
<ul>
  <li>(h) -- (303) 689-2159</li>
  <li>(c) -- (303) 618-7397</li>
</ul>
</p>
{% else %}
<p>Thank you for your application to adopt a rescued Ridgeback.  A representative of Colorado Rhodesian Ridgeback Rescue, (CRRR), will be in contact with you.  In the meantime, please browse our <a href={{ url_for('dogs.available') }}>available dogs</a>.</p>
{% endif %}
{% endblock %}

crrr/templates/root/email_volunteer.html
{% from "_helpers.html" import render, bool_render %}
<h1>Colorado Rhodesian Ridgeback Rescue Volunteer Form</h1>
<p>Submitted at {{ submitted_at }}</p>

<h2>Personal Information</h2>
{{ render(form.first_name) }}
{{ render(form.last_name) }}
{{ render(form.addr_1) }}
{{ render(form.addr_2) }}
{{ render(form.city) }}
{{ render(form.state) }}
{{ render(form.zip_code) }}
{{ render(form.phone_h) }}
{{ render(form.phone_c) }}
{{ render(form.phone_w) }}
<h2>Volunteering For</h2>
{{ bool_render(form.foster) }}
{{ bool_render(form.transport) }}
{{ bool_render(form.home_check) }}
{{ bool_render(form.adopter_check) }}
{{ bool_render(form.donate_crate) }}
{{ bool_render(form.donate_supplies) }}

crrr/templates/root/index.html
{% extends "layout.html" %}
{% block content %}
<pre class="snippet">
  <code>
    <b>Inge Trump</b>
    <em>Coordinator</em>
    <i class="fa fa-phone"></i>  (303) 689 - 2159
    <i class="fa fa-envelope"></i>  <a href="mailto:adoptions@crrr.org">Email</a>
  </code>
</pre>
<div>
<p>Colorado Rhodesian Ridgeback Rescue, CRRR, is an all-volunteer group
dedicated to providing rescue, care, and screened adoptions of pure bred and
mixed breed Rhodesian Ridgebacks in need.  A "rescue dog" is one that needs a
new home. Rescued Rhodesian Ridgebacks come to us from a variety of
circumstances. Some come from a family who can no longer care for them, others
come from animal shelters or are found as strays. Most of our dogs are one year
old or older, although every now and then we will have puppies available for
adoption.</p>
<p>All of our rescued Rhodesian Ridgebacks are cared for in foster homes. We
evaluate their temperament and needs to make the best match we can with an
adoptive home/family. ("Family" can be a single adult, adult partners, or
adults and children.)</p>
<p>We are often asked if a rescued Rhodesian Ridgeback will bond with his / her
new family, and the answer is, "Absolutely". There may be an adjustment period
of several days or weeks while they settle in with their new home and family.
Rescued dogs seem to sense they are wanted and loved by their new family; this
helps with the adjustment.</p>
<p>Veterinary medical and surgical care is provided by rescue funds when needed
for sick or injured rescued dogs. If necessary, we take our dogs for a
veterinary check up and immunizations.  All of the dogs are spayed / neutered
prior to being adopted. </p>
<p>As a 100% volunteer organization, we welcome donations.  The button at  the
bottom of the page will take you to PayPal, where you can make a secure
donation to our cause.</P>
<p>We are also always in need of foster homes who understand the breed. Please
consider <a href={{ url_for('root.volunteer') }}>volunteering</a> if you would be able to
provide a foster home for one of these great dogs until the right "forever"
home can be found.</p>
</div>
<aside>
   <h2>Thinking about buying a puppy?</h2>
   <p>Please make sure you go through a reputable breeder!</p>
   <p>Click <a href="http://www.illinoissheltierescue.com/puppymillstory.html" target="_blank">here</a> to learn about the relationship between puppy mills and pet shops, and <a href="http://www.illinoissheltierescue.com/howtobuyapuppy.html" target="_blank">here</a> for an informative article about choosing a reputable breeder.</p>
</aside>
{% endblock %}

crrr/templates/root/reset_password_email.html
<h2>CRRR Password Reset Request</h2>

<p>We have received your request to reset your password.  Please follow <a href={{ url_for('admin.reset_hash', hash=reset.hash, _external=True) }}>this link</a> within one hour to change your password.</p>

crrr/templates/root/volunteer.html
{% extends "layout.html" %}
{% block content %}
{% from "_helpers.html" import render, bool_render %}
{% if form %}
<h1>CRRR Volunteer Application</h1>
<p>
The CRRR depends on support from community members like yourself to be able to
provide a caring environment for our rescued Ridgebacks. We have numerous
oportunities for helping out, ranging from the time and emotionally intensive
fostering of dogs, to the shuffling of paperwork, to the screening of potential
adopters. If you are in any way interested in assisting us, please fill out the
form below. Thank you for your interest!
</p>
    <form method="POST" action={{ url_for('root.volunteer') }} class="pure-form pure-form-aligned" id="application">
    {{ form.hidden_tag() }}
    {% if form.errors %}
    <p class="missing">Oh no!  Your application hasn't passed our validation!
    Please ensure the following required fields are filled in properly:</p>
    <ul class="missing">
      {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
          <li>{{ form[field_name].label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
        <legend>Personal Information</legend>
        {{ render(form.first_name) }}
        {{ render(form.last_name) }}
        {{ render(form.addr_1) }}
        {{ render(form.addr_2) }}
        {{ render(form.city) }}
        {{ render(form.state) }}
        {{ render(form.zip_code) }}
        {{ render(form.phone_h) }}
        {{ render(form.phone_c) }}
        {{ render(form.phone_w) }}
        {{ render(form.email) }}
    </fieldset>
    <fieldset>
        <legend>Volunteering Information</legend>
        Please select all that you are able to assist with:<br />
        {{ bool_render(form.foster) }}
        {{ bool_render(form.transport) }}
        {{ bool_render(form.home_check) }}
        {{ bool_render(form.adopter_check) }}
        {{ bool_render(form.donate_crate) }}
        {{ bool_render(form.donate_supplies) }}
        <div class="pure-controls">
            {{ form.other_input.label(text=form.other() + " " + form.other_input(placeholder="Other..", class="pure-input-2-3")) }}
        </div>
    </fieldset>
    <div class="pure-controls">{{ form.submit(class="pure-button pure-button-primary") }}</div>
    </form>
{% else %}
Thank you for your interest in becoming a volunteer.  A representative of Colorado Rhodesian Ridgeback Rescue, (CRRR), will be in contact with you.<br />
{% endif %}
{% endblock %}